import { useQuery } from '@tanstack/react-query';
import { Activity, Clock3 } from 'lucide-react';
import { useState } from 'react';
import { AppCard, ErrorState, LoadingPanel, PageHeader } from '../../components/ui';
import { getAuditEvents } from '../../lib/audit-api';

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata' }).format(new Date());
export function ActivityPage() {
  const [hour, setHour] = useState<number | null>(null);
  const query = useQuery({ queryKey: ['today-activity'], queryFn: async ({ signal }) => { const first = await getAuditEvents({ page: 1, from: today(), to: today() }, signal); const all = [...first.data]; for (let page = 2; page <= first.meta.totalPages; page++) all.push(...(await getAuditEvents({ page, from: today(), to: today() }, signal)).data); return all; } });
  const events = query.data ?? [];
  const hourOf = (date: string) => Number(new Date(date).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', hour: 'numeric', hour12: false }));
  const counts = Array.from({ length: 24 }, (_, h) => events.filter(e => hourOf(e.timestampUtc) === h).length);
  const selected = hour === null ? events : events.filter(e => hourOf(e.timestampUtc) === hour);
  const max = Math.max(1, ...counts);
  return <div className="space-y-6"><PageHeader description="A complete view of what employees and administrators did today." title="Today activity" />{query.isPending ? <LoadingPanel label="Loading today activity" /> : query.isError ? <ErrorState message="Today activity could not be loaded." onRetry={() => void query.refetch()} /> : <><AppCard><div className="flex items-center gap-2"><Activity className="text-[var(--color-primary)]" size={19} /><h2 className="font-extrabold">Activity by hour</h2></div><p className="mt-1 text-xs text-[var(--color-text-muted)]">Click any bar to inspect exactly what happened during that hour.</p><div className="mt-6 flex h-48 items-end gap-1 border-b border-l border-[var(--color-border)] px-2">{counts.map((count, index) => <button aria-label={`${index}:00, ${count} events`} className={`group flex flex-1 flex-col justify-end ${hour === index ? 'bg-[var(--color-primary-soft)]' : ''}`} key={index} onClick={() => setHour(hour === index ? null : index)}><span className="mx-auto block w-full max-w-7 rounded-t bg-[var(--color-primary)]" style={{ height: `${Math.max(count ? 8 : 2, count / max * 150)}px` }} /></button>)}</div><div className="mt-2 flex justify-between text-[10px] text-[var(--color-text-muted)]"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div></AppCard><AppCard><div className="flex items-center gap-2"><Clock3 className="text-[var(--color-primary)]" size={18} /><h2 className="font-extrabold">{hour === null ? 'All activity today' : `Activity at ${String(hour).padStart(2, '0')}:00`}</h2></div><div className="mt-4 divide-y divide-[var(--color-border)]">{selected.map(event => <div className="py-4" key={event.id}><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{event.action.replaceAll('_', ' ')}</strong><span className="text-xs text-[var(--color-text-muted)]">{new Date(event.timestampUtc).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</span></div><p className="mt-1 text-sm">{event.actorWorkerId ?? 'System'} · {event.targetType} {event.targetId ? `· ${event.targetId}` : ''}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">Result: {event.result}{event.reasonCode ? ` · ${event.reasonCode}` : ''}</p>{event.metadata ? <details className="mt-2 text-xs"><summary className="cursor-pointer font-bold">View what changed</summary><pre className="mt-2 overflow-auto rounded bg-[var(--color-surface-tint)] p-2">{JSON.stringify(event.metadata, null, 2)}</pre></details> : null}</div>)}</div></AppCard></>}</div>;
}
